version: "3.9"
services:
  db:
    image: postgres:15.4-alpine
    container_name: db
    ports:
      - "5432:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - data:/tukitoki/db

  timetable-service:
    image: tokichii/timetable:latest
    container_name: timetable
    restart: always
    build:
      context: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SERVER_PORT=${SERVER_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

volumes:
  data: