version: "3.9"
services:
  timetable-service:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/timetable
      - DB_USER=postgres
      - DB_PASS=postgres
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timetable