settings:
  server:
    port: ${SERVER_PORT:8080}
  db:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/timetable}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
  timetable:
    frontend-path: ${FRONT_PATH:http://localhost:4200}

server:
  port: ${settings.server.port}
  servlet:
    context-path: "/api/timetable"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${settings.db.url}
    username: ${settings.db.username}
    password: ${settings.db.password}
  jpa:
    hibernate:
      ddl-auto: update

optaplanner:
  solver:
    termination:
      spent-limit: 30m
      best-score-limit: 0hard/0soft
jwt:
  secret-key: ${PRIVATE_KEY:fe1501ba654b1adfaf05cc4195680bd04d6aa2afea771b30e9db3956cc411324}
  access-validity: 3600000
  refresh-validity: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs