name: JavaCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: tokichii/demo
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: copy files
        run: |
          echo "${{ SECRETS.ENV_FILE }}" >> .env
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/tokichii/timetable
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete .env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/tokichii/timetable
      - name: deploy
        run: |
          ssh -tt -i $HOME/.ssh/key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          'cd $HOME/timetable ; sudo docker-compose --env-file .env pull; sudo docker-compose --env-file .env down --timeout=20; sudo docker-compose --env-file .env up -d ; sudo docker image prune -f || true'
