name: JavaCI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build & push docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: tokichii/timetable
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: okteto context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: deploy
        uses: okteto/pipeline@latest
        with:
          name: timetable
          timeout: 8m
          variables: ${{ secrets.ENV_FILE }}